/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package App;

import Controller.ProjetoController;

import Model.Project;

import java.util.List;


public class App {
    
    public static void main(String[] args) throws Exception {
      
     
       // TaskController tc = TaskController();
        
        //Task task = new Task ();
         testeController();
      
      
      
   
      
      
    }
    
    public static  void testeController() throws Exception{
      ProjetoController projetoController = new ProjetoController();
     
      
      Project projeto = new Project();
      projeto.setName("Projeto teste");
      projeto.setDescription("gkfjmkdgdkjg");
      
      projetoController.save(projeto);
      projeto.setName("Novo Projeto teste");
      projetoController.update(projeto);
      
      List<Project> listaProjetos = projetoController.getAll();
      
      System.out.println("numero de projetos: "+ listaProjetos.size());
      
      
       projetoController.removeById(30);
       projetoController.removeById(31);
      
      
      
      
      
        
    }
}
